import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

/// Thrown by [AuthService] operations with a user-friendly message that can
/// be shown directly in a snackbar.
class AuthException implements Exception {
  const AuthException(this.message);

  final String message;

  @override
  String toString() => message;
}

/// Wraps Firebase Authentication and Google Sign-In behind a single API.
///
/// The only class in the app allowed to talk to FirebaseAuth directly.
/// Dependencies are injectable so tests can substitute fakes.
class AuthService {
  AuthService({FirebaseAuth? firebaseAuth, GoogleSignIn? googleSignIn})
      : _firebaseAuth = firebaseAuth ?? FirebaseAuth.instance,
        _googleSignIn = googleSignIn ?? GoogleSignIn.instance;

  final FirebaseAuth _firebaseAuth;
  final GoogleSignIn _googleSignIn;

  /// OAuth 2.0 *web* client id of the Firebase project — required by the
  /// Android Credential Manager to return an ID token.
  ///
  /// Generated by Firebase when the Google sign-in provider is enabled;
  /// found in google-services.json as the `oauth_client` entry with
  /// `client_type: 3`.
  static const String _googleServerClientId =
      '788744109552-5jql8kqq0j521r7cj5vhc9attdkq9tai.apps.googleusercontent.com';

  bool _googleInitialized = false;

  User? get currentUser => _firebaseAuth.currentUser;

  Stream<User?> authStateChanges() => _firebaseAuth.authStateChanges();

  Future<void> signInWithEmail(String email, String password) {
    return _guard(
      () => _firebaseAuth.signInWithEmailAndPassword(
        email: email,
        password: password,
      ),
    );
  }

  Future<void> registerWithEmail(String email, String password) {
    return _guard(
      () => _firebaseAuth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      ),
    );
  }

  Future<void> sendPasswordResetEmail(String email) {
    return _guard(() => _firebaseAuth.sendPasswordResetEmail(email: email));
  }

  /// Runs the Google account picker and signs the user into Firebase.
  ///
  /// Returns false if the user dismissed the picker without choosing an
  /// account; throws [AuthException] on real failures.
  Future<bool> signInWithGoogle() async {
    try {
      if (!_googleInitialized) {
        await _googleSignIn.initialize(serverClientId: _googleServerClientId);
        _googleInitialized = true;
      }
      final GoogleSignInAccount account = await _googleSignIn.authenticate();
      final String? idToken = account.authentication.idToken;
      if (idToken == null) {
        throw const AuthException(
          'Google sign-in failed: no ID token returned.',
        );
      }
      await _firebaseAuth.signInWithCredential(
        GoogleAuthProvider.credential(idToken: idToken),
      );
      return true;
    } on GoogleSignInException catch (e) {
      if (e.code == GoogleSignInExceptionCode.canceled) {
        return false;
      }
      throw AuthException(
        'Google sign-in failed: ${e.description ?? e.code.name}',
      );
    } on FirebaseAuthException catch (e) {
      throw AuthException(_messageForCode(e));
    }
  }

  Future<void> signOut() async {
    await _firebaseAuth.signOut();
    if (_googleInitialized) {
      await _googleSignIn.signOut();
    }
  }

  Future<void> _guard(Future<Object?> Function() action) async {
    try {
      await action();
    } on FirebaseAuthException catch (e) {
      throw AuthException(_messageForCode(e));
    }
  }

  static String _messageForCode(FirebaseAuthException e) {
    return switch (e.code) {
      'invalid-credential' ||
      'wrong-password' ||
      'user-not-found' =>
        'Incorrect email or password.',
      'invalid-email' => 'That email address is not valid.',
      'user-disabled' => 'This account has been disabled.',
      'email-already-in-use' =>
        'An account already exists with this email. Try signing in.',
      'weak-password' => 'That password is too weak. Use at least 6 characters.',
      'too-many-requests' => 'Too many attempts. Please try again later.',
      'network-request-failed' =>
        'Network error. Check your internet connection.',
      _ => e.message ?? 'Authentication failed. Please try again.',
    };
  }
}
